name: 'klaviyo_source_integration_tests'
version: '0.1.0'
config-version: 2
profile: 'integration_tests'


vars:
  klaviyo_source: 
    event_table: "{{ ref('event') }}"


seeds:
  klaviyo_source_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    # event:
    #   +column_types:
    #     time: timestamp